/**
 * TDD Seam 2: Browser/operator mutation HTTP seam 测试
 * 验证 Issue #28 规范：
 * 1. a legitimate request generated by the locally served Rally UI succeeds;
 * 2. wrong/missing application-layer authorization and materially invalid Origin/Host fail before canonical mutation;
 * 3. rejection proves zero state change.
 */

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { createProjectRegistry } from '../../src/registry/project-registry.js';
import { startStatusSurfaceServer } from '../../src/surface/surface-server.js';

describe('TDD Seam 2: Browser/operator mutation HTTP boundary seam', () => {
  let registry;
  let serverHandle;
  let baseUrl;
  let validSessionToken;

  const testBinding = {
    binding_id: 'boundary-test-proj',
    binding_revision: 1,
    browser: { provider: 'chatgpt', conversation_id: 'conv-bound-browser' },
    ide_endpoints: [{
      endpoint_id: 'ide-primary',
      endpoint_revision: 1,
      conversation_id: 'conv-bound-ide',
      workspace_identity: '/ws/bound',
      repository_identity: 'github.com/org/bound'
    }],
    capabilities: ['read', 'write'],
    paused: false
  };

  before(async () => {
    registry = createProjectRegistry();
    const core = registry.registerProject({ binding: testBinding });
    core.recordEndpointObservation('browser', {
      trusted: true,
      latest_completed_cursor: 'cur-bound-1',
      provider: 'chatgpt',
      conversation_id: 'conv-bound-browser',
      endpoint_revision: 1
    });

    serverHandle = await startStatusSurfaceServer({ registry, port: 0 });
    baseUrl = serverHandle.url;
    validSessionToken = serverHandle.sessionToken;
  });

  after(async () => {
    if (serverHandle) {
      await serverHandle.close();
    }
  });

  it('1. 渲染的本地 UI (GET /) 包含合法 session token meta 标签', async () => {
    const res = await fetch(`${baseUrl}/`);
    assert.equal(res.status, 200);
    const html = await res.text();
    assert.match(html, /<meta\s+name=["']rally-session-token["']\s+content=["'][a-f0-9]{32,}["']/i);
  });

  it('2. 携带缺失 application-layer session token 的突变请求必须被拦截 (403)，且零状态改变', async () => {
    const res = await fetch(`${baseUrl}/api/projects/boundary-test-proj/endpoints/browser/handled`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
        // 故意缺少 X-Rally-Session-Token
      },
      body: JSON.stringify({ expected_cursor: 'cur-bound-1' })
    });

    assert.equal(res.status, 403);
    const data = await res.json();
    assert.equal(data.success, false);
    assert.match(data.reason, /MISSING_OR_INVALID_SESSION_TOKEN/i);

    // 零状态改变验证
    const proj = registry.getProject('boundary-test-proj').getSnapshot();
    assert.equal(proj.endpoints.browser.result_state, 'NEW');
    assert.equal(proj.endpoints.browser.last_handled_cursor, null);
  });

  it('3. 携带错误 application-layer session token 的突变请求必须被拦截 (403)，且零状态改变', async () => {
    const res = await fetch(`${baseUrl}/api/projects/boundary-test-proj/endpoints/browser/handled`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Rally-Session-Token': 'wrong-forged-token-1234567890'
      },
      body: JSON.stringify({ expected_cursor: 'cur-bound-1' })
    });

    assert.equal(res.status, 403);
    const data = await res.json();
    assert.equal(data.success, false);
    assert.match(data.reason, /MISSING_OR_INVALID_SESSION_TOKEN/i);

    // 零状态改变验证
    const proj = registry.getProject('boundary-test-proj').getSnapshot();
    assert.equal(proj.endpoints.browser.result_state, 'NEW');
  });

  it('4. 跨源恶意外站 (Origin: http://evil.com) 即使伪造了 token 也必须被拦截 (403)，且零状态改变', async () => {
    const res = await fetch(`${baseUrl}/api/projects/boundary-test-proj/endpoints/browser/handled`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Origin': 'http://evil.com',
        'X-Rally-Session-Token': validSessionToken
      },
      body: JSON.stringify({ expected_cursor: 'cur-bound-1' })
    });

    assert.equal(res.status, 403);
    const data = await res.json();
    assert.equal(data.success, false);
    assert.match(data.reason, /UNAUTHORIZED_ORIGIN/i);

    // 零状态改变验证
    const proj = registry.getProject('boundary-test-proj').getSnapshot();
    assert.equal(proj.endpoints.browser.result_state, 'NEW');
  });

  it('5. 恶意 Host 头 (Host: attacker.example.com) 必须被拦截 (403)，且零状态改变', async () => {
    const postData = JSON.stringify({ expected_cursor: 'cur-bound-1' });
    const parsedUrl = new URL(baseUrl);

    const { statusCode, body } = await new Promise((resolve, reject) => {
      const req = http.request({
        hostname: parsedUrl.hostname,
        port: parsedUrl.port,
        path: '/api/projects/boundary-test-proj/endpoints/browser/handled',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(postData),
          'Host': 'attacker.example.com',
          'X-Rally-Session-Token': validSessionToken
        }
      }, (res) => {
        let raw = '';
        res.setEncoding('utf8');
        res.on('data', chunk => { raw += chunk; });
        res.on('end', () => {
          try {
            resolve({ statusCode: res.statusCode, body: JSON.parse(raw) });
          } catch (e) {
            resolve({ statusCode: res.statusCode, body: raw });
          }
        });
      });
      req.on('error', reject);
      req.write(postData);
      req.end();
    });

    assert.equal(statusCode, 403);
    assert.equal(body.success, false);
    assert.match(body.reason, /INVALID_HOST_HEADER/i);

    // 零状态改变验证
    const proj = registry.getProject('boundary-test-proj').getSnapshot();
    assert.equal(proj.endpoints.browser.result_state, 'NEW');
  });

  it('6. 来自合法本地 UI 的正常请求（具备合法 Session Token）成功执行突变', async () => {
    const res = await fetch(`${baseUrl}/api/projects/boundary-test-proj/endpoints/browser/handled`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Rally-Session-Token': validSessionToken
      },
      body: JSON.stringify({ expected_cursor: 'cur-bound-1' })
    });

    assert.equal(res.status, 200);
    const data = await res.json();
    assert.equal(data.success, true);

    // 状态成功推进
    const proj = registry.getProject('boundary-test-proj').getSnapshot();
    assert.equal(proj.endpoints.browser.result_state, 'NO_NEW_RESULT');
    assert.equal(proj.endpoints.browser.last_handled_cursor, 'cur-bound-1');
  });
});
